<a href="https://colab.research.google.com/github/CamelGoong/R_Practicing/blob/main/Week2_Rprogramming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2-1 벡터 및 행렬 생성 

In [ ]:
x<-c(1,3,5,7,9)

In [ ]:
x[3] # R언어는 인덱스가 1부터 시작함.

[1] 5

In [ ]:
x[-1] # 첫번째 원소를 삭제. 뒤에서 첫번째 원소를 인덱싱해오라는 의미가 아님.

[1] 3 5 7 9

In [ ]:
x1<-x[-c(1,2)]
x1

[1] 5 7 9

In [ ]:
x2<-x[-c(1:3)] # 첫번째부터 세번째값까지 삭제 / c[1:3]이 아님.
x2

[1] 7 9

벡터 생성(seq 함수 사용)

In [ ]:
y1<-seq(0,10, length = 20) # 0~10 사이의 벡터를 20개 생성
y1

[1]  0.0000000  0.5263158  1.0526316  1.5789474  2.1052632  2.6315789
 [7]  3.1578947  3.6842105  4.2105263  4.7368421  5.2631579  5.7894737
[13]  6.3157895  6.8421053  7.3684211  7.8947368  8.4210526  8.9473684
[19]  9.4736842 10.0000000

In [ ]:
y2<-seq(0,10, by = 0.5) # 0.5 간격으로 생성
y2

[1]  0.0  0.5  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0
[16]  7.5  8.0  8.5  9.0  9.5 10.0

벡터(rep 함수 사용)

In [ ]:
z1<-rep(1:4, 2) # 1~4까지 2번 반복
z1

[1] 1 2 3 4 1 2 3 4

In [ ]:
z2<-rep(1:2, 5) # 1~2까지 5번 반복
z2

[1] 1 2 1 2 1 2 1 2 1 2

벡터 결합(행과 열을 기준)

In [ ]:
# cbind: column bind(열 기준으로 결합)

c1<-c(2, 4, 6, 8, 10)
c2<-cbind(x, c1)
c2

x c1
[1,] 1  2
[2,] 3  4
[3,] 5  6
[4,] 7  8
[5,] 9 10

In [ ]:
# rbind: row bind(행으로 결합)
c3<-rbind(x,c1)
c3

[,1] [,2] [,3] [,4] [,5]
x  1    3    5    7     9  
c1 2    4    6    8    10

벡터이름주기(names)

In [ ]:
gender<-c(0,1)
names(gender)<-c("female", "male")
gender

female   male 
     0      1

범주형 변수 생성(factor 사용)

In [ ]:
size<-c("S", "M", "L", "XL")
size_factor<-factor(size)
size_factor

[1] S  M  L  XL
Levels: L M S XL

In [ ]:
is.factor(size_factor)

[1] TRUE

범주형 변수 생성(factor 사용) - 순서를 정의한 factor 생성 

In [ ]:
size_factor3<-factor(size, ordered = T, levels = c("S", "M", "L", "XL"))
size_factor3

[1] S  M  L  XL
Levels: S < M < L < XL

행렬의 생성(matrix 함수 이용) - 행의 수나 열의 수를 입

In [ ]:
m1<-matrix(1:10, nrow = 2) # 2개의 컬럼을 생성
m1

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [ ]:
m2<-matrix(1:6, ncol = 3) # 3개의 열을 생성
m

ERROR: ignored

In [ ]:
# 원래는 matrix 함수는 1열부터 채우는 것이 default이지만, byrow = T 옵션을 사용해서 1행부터 채우도록 할 수 있음. 
m3<-matrix(1:6, nrow = 2, byrow = T)
m3

고차원 행렬(array를 이용하여 생성)

In [ ]:
a1<-array(c(1:18), dim = c(3,3,2)) # 여기서는 각각 c를 씌어준 것에 유의 
# 3*3행짜리 행렬이 2개가 생기는 것
a1

2-2 벡터와 행렬의 연산 

벡터의 연산 

In [ ]:
# %% 나머지 %/% 몫 | or

2^3
2**3

[1] 8

[1] 8

In [ ]:
7%%5 # 나머지
7%/%5 # 몫

[1] 2

[1] 1

# 행렬의 연산 

In [ ]:
# %*% 행렬 간의 곱
# t(A) 전치행렬
# solve(A,b) 방정식을 풀때 

In [ ]:
m1<-matrix(1:10, nrow = 2)
m1

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [ ]:
# 행렬의 차원 알아보기 dim
dim(m1) # 2행 5열

[1] 2 5

In [ ]:
# 전치행렬(transpose) 구하기
tm2<-t(m2)
tm2

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [ ]:
# determinant 구하기(det) / 역행렬을 구하는데에도 사용.

d1<-matrix(1:4, nrow = 2, byrow = T)
d1
det(d1)

# 2*2말고 고차원 행렬에 대해서도 det를 간단하게 구할 수 있음.

[,1] [,2]
[1,] 1    2   
[2,] 3    4

[1] -2

In [ ]:
# 역행렬(inverse) 구하기(solve)
d1_inv<-solve(d1)
d1_inv

[,1] [,2]
[1,] -2.0  1.0
[2,]  1.5 -0.5

In [ ]:
# d1과 d1_inv를 곱하면 identity matrix가 나오는지 확인하기
d1 %*% d1_inv

[,1]         [,2]
[1,] 1.000000e+00 0   
[2,] 8.881784e-16 1

In [ ]:
# 역행렬을 이용한 방정식 해 구하기(solve)
a<-matrix(c(3,1,2,1), nrow = 2, ncol = 2)
b<-matrix(c(8,2), nrow = 2, ncol = 1)
a
b

[,1] [,2]
[1,] 3    2   
[2,] 1    1

[,1]
[1,] 8   
[2,] 2

In [ ]:
solve(a, b) # x, y에 대한 해 구하기

[,1]
[1,]  4  
[2,] -2

In [ ]:
# 도움말 보기
help(solve)

고유치(eigenvalue)와 고유벡터(eigenvector)

In [ ]:
# xTx를 통계에서는 공분산행렬이라고 함. -> 이를 통해, 통계에서는 다변량분석을 하기도 함.
# 공분산행렬의 특성을 파악하기 위해서 구하는 것이 eigenvalue와 eigenvector임.

e1<-eigen(t(x) %*% x)
e1

eigen() decomposition
$values
[1] 165

$vectors
     [,1]
[1,]    1


2-3 간단한 함수생성 및 루프 

In [69]:
# square 함수 만들기

# input값이 x이고 return값이 x*x인 square라는 이름의 function 생성

square<-function(x){
  return(x*x)
} 

In [70]:
square(9)

[1] 81

In [71]:
square(1:3)

[1] 1 4 9

In [72]:
# dif function
dif <- function(x,y){
  return(x-y)
}

dif(20, 10)

[1] 10

In [73]:
rootdif<-function(x,y){
  return(sqrt(x-y))
}

rootdif(20,10)

[1] 3.162278

In [74]:
# 기존함수: round - 소수점 자리를 조정
round(5.14846) # 옵션없이하면 그냥 정수가 나옴.
round(5.14846, 2) # 소수점 둘째자리까지 표현 

[1] 5

[1] 5.15

In [77]:
round(rootdif(20, 10))
round(rootdif(20, 10), 2)

[1] 3

[1] 3.16

루프문(for)

In [78]:
# 1~10까지의 수 중에서 3으로 나눈 나머지가 1이 아닌 수를 출력
for(i in 1:10){
  if(i%%3 == 1){
    next() # 다음 숫자로 루프를 돌리는 것. python의 continue랑 같은듯!
  }
  print(i)
}

[1] 2
[1] 3
[1] 5
[1] 6
[1] 8
[1] 9


In [79]:
# 1부터 10까지 더해가며 합이 20보다 작을 때까지 출력

sum = 0
for(i in 1:10){
  sum<-sum + i
  if(sum >20){
    break
  }
  print(sum)
}

[1] 1
[1] 3
[1] 6
[1] 10
[1] 15


루프문(while) - condition이 있음.

In [81]:
# 1부터 5까지를 출력

y = 0
while(y < 5){print(y<-y+1)}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
